name: test
on: pull_request
jobs:
  test:
    name: Test tfmodule
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: "1.14.1"
    - name: Test all
      env:
        GO111MODULE: on
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get golang.org/x/lint/golint
        make test
