name: release
on:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    name: Release Parade
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: "1.14.1"
    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: latest
        args: release --rm-dist
